version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"  # allows us to access the web console
  
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    ports:
    - "5672:5672"       # AMQP protocol port
    - "15672:15672"  # management plugin port"
  
  placement:
    image: "daprio/dapr:1.14.2"
  
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"

  savingsondapr.api:
    build:
      context: .
      dockerfile: ./SavingsOnDapr.Api/Dockerfile
    depends_on:
      - postgres
      - placement
      - rabbitmq 

  savingsondapr.api-dapr:
    image: "daprio/daprd:1.14.2"
    network_mode: "service:savingsondapr.api"
    depends_on:
      - savingsondapr.api