version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"  # allows us to access the web console
  
  placement:
    image: "daprio/dapr:1.14.2"

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
    - "5672:5672"       # AMQP protocol port
    - "15672:15672"  # management plugin port"
  
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"

  savingsondapr.api:
    build:
      context: .
      dockerfile: ./SavingsOnDapr.Api/Dockerfile
    depends_on:
      - postgres

  savingsondapr.api-dapr:
    image: "daprio/daprd:1.14.2"
    network_mode: "service:savingsondapr.api"
    depends_on:
      postgres:
        condition: service_started
      savingsondapr.api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  savingsondapr.eventstore:
    build:
      context: .
      dockerfile: ./SavingsOnDapr.EventStore/Dockerfile
    depends_on:
      - postgres

  savingsondapr.eventstore-dapr:
    image: "daprio/daprd:1.14.2"
    network_mode: "service:savingsondapr.eventstore"
    depends_on:
      postgres:
        condition: service_started
      savingsondapr.eventstore:
        condition: service_started
      rabbitmq:
        condition: service_healthy


