version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"  # allows us to access the web console
  
  placement:
    image: "daprio/dapr:1.15.1"
    command: ["./placement", "--port", "50000"]
    ports:
      - "50000:50000"

  scheduler:
    image: "daprio/dapr:1.15.1"
    command: ["./scheduler", "--port", "50007"]
    ports:
      - "50007:50007"
    # WARNING - This is a tmpfs volume, your state will not be persisted across restarts
    volumes:
    - type: tmpfs
      target: /data
      tmpfs:
        size: "64m"

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
    - "5672:5672"       # AMQP protocol port
    - "15672:15672"  # management plugin port"
  
  redis:
    image: redis
    command: redis-server --port 6379 --requirepass "examplexamplexample" --maxmemory 4mb --maxmemory-policy allkeys-lru
    ports:
    - "6379:6379"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./dbinit:/docker-entrypoint-initdb.d"
      - "pgdata:/var/lib/postgresql/data"

  savingsondapr.api:
    build:
      context: .
      dockerfile: ./SavingsOnDapr.Api/Dockerfile
    depends_on:
      - postgres

  savingsondapr.api-dapr:
    image: "daprio/daprd:1.15.1"
    network_mode: "service:savingsondapr.api"
    depends_on:
      postgres:
        condition: service_started
      savingsondapr.api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  currencyexchange.api:
    build:
      context: .
      dockerfile: ./CurrencyExchange.Api/Dockerfile
    depends_on:
      - postgres
  
  currencyexchange.api-dapr:
    image: "daprio/daprd:1.15.1"
    network_mode: "service:currencyexchange.api"
    depends_on:
      postgres:
        condition: service_started
      currencyexchange.api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  
  savingsondapr.eventstore:
    build:
      context: .
      dockerfile: ./SavingsOnDapr.EventStore/Dockerfile
    depends_on:
      - postgres

  savingsondapr.eventstore-dapr:
    image: "daprio/daprd:1.15.1"
    network_mode: "service:savingsondapr.eventstore"
    depends_on:
      postgres:
        condition: service_started
      savingsondapr.eventstore:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  dashboard.api:
    build:
      context: .
      dockerfile: ./Dashboard.Api/Dockerfile

  dashboard.api-dapr:
    image: "daprio/daprd:1.15.1"
    network_mode: "service:dashboard.api"
    depends_on:
      savingsondapr.api:
        condition: service_started
volumes:
  pgdata:
    external: true


