version: '3.4'
services:
  savingsondapr.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3605
      - NAMESPACE=savings
      - ConnectionStrings__DocumentStore=host='postgres';username='postgres';password='example';port='5432';database='doc-store'
    ports:
      - "5136:80"

  savingsondapr.api-dapr:
    command: ["./daprd",
      "--app-id", "dapr-savings-api",
      "--app-port", "80",
      "--dapr-http-port", "3605",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"

  postgres:
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dapr-store