apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: publish-events
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "30 * * * * *"
  - name: direction
    value: "input"