apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: publish-events
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "0 * * * * *"
  - name: direction
    value: "input"
  - name: route
    value: /api/platform/publish-events
scopes:
- dapr-savings-api