apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: accrue-interest
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 10m"
  - name: direction
    value: "input"
  - name: route
    value: /api/platform/accrue-interest