apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-std
version: v1alpha1

spec:
  policies: # Required
    retries:
      DaprBuiltInServiceRetries: 
      # Overrides default retry behavior for service-to-service calls
        policy: constant
        duration: 5s
        maxRetries: 10
      DefaultPubsubComponentInboundRetryPolicy:
      # Overrides default retry behavior for Pub/sub subscriptions 
        policy: exponential
        maxInterval: 3m
        maxRetries: 7
